[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
staking_program = "4i4Vv4AHPpXoDpsK73CxHURMaQXtWBA8VWcuJ9h79qiT"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/manthan/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
